export const topTravelDestinations = [
  { name: 'Cancun, Mexico', iataCode: 'CUN' },
  { name: 'London, United Kingdom', iataCode: 'LHR' },
  { name: 'Punta Cana, Dominican Republic', iataCode: 'PUJ' },
  { name: 'Paris, France', iataCode: 'CDG' },
  { name: 'Puerto Vallarta', iataCode: 'PVR' },
  { name: 'Rome', iataCode: 'FCO' },
  { name: 'Milan', iataCode: 'MXP' },
  { name: 'Florence', iataCode: 'FLR' },
  { name: 'Lisbon', iataCode: 'LIS' },
  { name: 'Marseilles', iataCode: 'MRS' },
  { name: 'Sicily', iataCode: 'CTA' },
  { name: 'Sardinia', iataCode: 'CAG' },
  { name: 'Corsica', iataCode: 'AJA' },
  { name: 'Hyeres', iataCode: 'TLN' },
  { name: 'Spokane', iataCode: 'GEG' },
  { name: 'porto', iataCode: 'OPO' },
  { name: 'Bora Bora', iataCode: 'BOB' },
  { name: 'Phuket', iataCode: 'HKT' },
  { name: 'Ho Chi Minh city', iataCode: 'SGN' },
  { name: 'Mexico City', iataCode: 'MEX' },
  { name: 'Phnom Penh', iataCode: 'PNH' },
  { name: 'Hanoi', iataCode: 'HAN' },
  { name: 'Tulum', iataCode: 'CUN' }, // Closest major airport is Cancun
  { name: 'Bali', iataCode: 'DPS' },
  { name: 'Sidney', iataCode: 'SYD' },
  { name: 'Tokyo, Japan', iataCode: 'NRT' },
  { name: 'Cabo San Lucas, Mexico', iataCode: 'SJD' },
  { name: 'Tijuana', iataCode: 'TIJ' },
  { name: 'Dubai, United Arab Emirates', iataCode: 'DXB' },
  { name: 'Barcelona, Spain', iataCode: 'BCN' },
  { name: 'Ponce', iataCode: 'PSE' },
  { name: 'New York City', iataCode: 'JFK' },
  { name: 'Las Vegas', iataCode: 'LAS' },
  { name: 'Orlando', iataCode: 'MCO' },
  { name: 'Los Angeles', iataCode: 'LAX' },
  { name: 'Chicago', iataCode: 'ORD' },
  { name: 'Miami', iataCode: 'MIA' },
  { name: 'San Francisco', iataCode: 'SFO' },
  { name: 'Honolulu', iataCode: 'HNL' },
  { name: 'Bangkok, Thailand', iataCode: 'BKK' },
  { name: 'Medellin, Colombia', iataCode: 'MDE' },
  { name: 'Vienna', iataCode: 'VIE' },
  { name: 'Brussels, Belgium', iataCode: 'BRU' },
  { name: 'Bogota', iataCode: 'BOG' },
  { name: 'New Orleans', iataCode: 'MSY' },
  { name: 'Nashville', iataCode: 'BNA' },
  { name: 'Boston', iataCode: 'BOS' },
  { name: 'San Diego', iataCode: 'SAN' },
  { name: 'Seattle', iataCode: 'SEA' },
  { name: 'Austin', iataCode: 'AUS' },
  { name: 'Denver', iataCode: 'DEN' },
  { name: 'Charleston', iataCode: 'CHS' },
  { name: 'Savannah', iataCode: 'SAV' },
  { name: 'Portland', iataCode: 'PDX' },
  { name: 'Philadelphia', iataCode: 'PHL' },
  { name: 'Phoenix', iataCode: 'PHX' },
  { name: 'San Antonio', iataCode: 'SAT' },
  { name: 'Santa Fe', iataCode: 'SAF' },
  { name: 'Sedona', iataCode: 'PHX' }, // Closest major airport is Phoenix
  { name: 'Maui', iataCode: 'OGG' },
  { name: 'Kauai', iataCode: 'LIH' },
  { name: 'Anchorage', iataCode: 'ANC' },
  { name: 'Salt Lake City', iataCode: 'SLC' },
  { name: 'Minneapolis', iataCode: 'MSP' },
  { name: 'Houston', iataCode: 'IAH' },
  { name: 'Dallas', iataCode: 'DFW' },
  { name: 'Atlanta', iataCode: 'ATL' },
  { name: 'Charlotte', iataCode: 'CLT' },
  { name: 'Newport', iataCode: 'PVD' }, // Closest major airport is Providence
  { name: 'Virginia Beach', iataCode: 'ORF' },
  { name: 'Kyoto', iataCode: 'KIX' }, // Closest major airport is Osaka Kansai
  { name: 'Prague', iataCode: 'PRG' },
  { name: 'Fiji', iataCode: 'NAN' },
  { name: 'Seychelles', iataCode: 'SEZ' },
  { name: 'Barbados', iataCode: 'BGI' },
  { name: 'Mauritius', iataCode: 'MRU' },
  { name: 'Rio de Janeiro', iataCode: 'GIG' },
  { name: 'Sao Paulo', iataCode: 'GRU' },
  { name: 'Cartagena', iataCode: 'CTG' },
  { name: 'Lima', iataCode: 'LIM' },
  { name: 'Minneapolis', iataCode: 'MSP' },
  { name: 'Kansas City', iataCode: 'MCI' },
  { name: 'Detroit', iataCode: 'DTW' },
  { name: 'Milwaukee', iataCode: 'MKE' },
  { name: 'Madison', iataCode: 'MSN' },
  { name: 'Costa Rica', iataCode: 'SJO' }, // Closest major airport is San Jose
  { name: 'Bahamas', iataCode: 'NAS' },
  { name: 'Maldives', iataCode: 'MLE' },
  { name: 'Budapest', iataCode: 'BUD' },
  { name: 'Dublin, Ireland', iataCode: 'DUB' },
  { name: 'Sydney, Australia', iataCode: 'SYD' },
  { name: 'Amsterdam, Netherlands', iataCode: 'AMS' },
  { name: 'Cape Town, South Africa', iataCode: 'CPT' },
  { name: 'St. Louis', iataCode: 'STL' },
  { name: 'Berlin', iataCode: 'BER' },
  { name: 'Vancouver', iataCode: 'YVR' },
  { name: 'Milwaukee', iataCode: 'MKE' },
  { name: 'Tampa', iataCode: 'TPA' },
  { name: 'Pittsburgh', iataCode: 'PIT' },
];
